### ISSUE TITLE
Tempo minimo di campinamento

### ISSUE THREAD

**Issue by lucci-spinitalia** [henry-spinitalia/Alma3d#1]
Nel manuale interno viene riportato che il tempo di campionamento minimo da utilizzare è di 1 ms. Sebbene questo sia il tempo minimo accettato dal motore, quello supportato dal programma canopenshell è di 10 ms, a causa del rallentamento dovuto al loop principale ed alla gestione degli eventi.

Sarebbe opportuno sostituire nel codice un livello minimo di 10 ms.

**Comment by henry-spinitalia** [comment]
Corretto
