### ISSUE TITLE
Copia del file di log nel modulo kinematic

### ISSUE THREAD

**Issue by lucci-spinitalia** [henry-spinitalia/Alma3d#5]
Alla riga 872 del modulo kinematic, nella funzione utilizzata per copiare il file, i nomi di sorgente e destinazione sono scambiati.

Sostituire

shutil.copyfile(filename, "{}simulazione_{}.csv".format(self.tripod.config.LOG_PATH, filename_complete))

con
shutil.copyfile(filename_complete, "{}simulazione_{}.csv".format(self.tripod.config.LOG_PATH, filename))

**Comment by henry-spinitalia** [comment]
Corretto, nell'eliminazione dell'MD5sum è stato creato il problema
