### ISSUE TITLE
Errore nell'apertura file per il parser cvs in kinematic

### ISSUE THREAD

**Issue by lucci-spinitalia** [henry-spinitalia/Alma3d#6]
Nel modulo kinematic, alla riga 887, l'apertura del file dovrebbe essere fatta con il path completo.

Sostituire

f = open(filename, 'rb')

con 

f = open(filename_complete, 'rb')

**Comment by henry-spinitalia** [comment]
Corretto, nell'eliminazione dell'MD5sum è stato creato il problema
